name: Run tests and publish

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: Node version
        default: '18'
        type: choice
        options:
          - '12'
          - '14'
          - '15'
          - '16'
          - '17'
          - '18'

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    with:
      node-version: ${{ inputs.node-version }}

  release-npmjs-registry:
    name: Release to npmjs registry
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: npmjs
      url: https://www.npmjs.com/package/useful-library
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
