name: Run tests and publish

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '**.md'
      - 'tests/**'
  workflow_dispatch:

jobs:

  build:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
         - 12
         - 14
         - 15  
         - 16
         - 17
         - 18       
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test

  release:
    name: Release to npm
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
