name: Check Markdown

on:
  pull_request:
    paths:
      - '**.md'

jobs:
  check-markdown:
    name: Check Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nosborn/github-action-markdown-cli@v3
        with:
          files: .
