name: Build

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - '**.md'
      - 'tests/**'
  workflow_dispatch:

jobs:

  audit:
    name: Audit packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit packages
        run: npm audit --audit-level moderate
        env:
          CI: true

  build:
    name: Node ${{ matrix.node_version }}
    needs: audit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
         - 12
         - 14
         - 15  
         - 16
         - 17
         - 18       
    steps:
      - uses: actions/checkout@v3
      - id: build
        uses: ./.github/actions/build
        with:
          node_version: ${{ matrix.node_version }}
