name: PR build

on:
  pull_request:
  workflow_dispatch:

jobs:

  audit:
    name: Audit packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit packages
        run: npm audit --audit-level moderate
        env:
          CI: true

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: true
      matrix:
        language: [javascript]
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  build:
    name: Build with Node ${{ matrix.node_version }}
    needs:
      - audit
      - analyze
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
         - 12
         - 14
         - 15  
         - 16
         - 17
         - 18       
    steps:
      - uses: actions/checkout@v3
      - id: build
        uses: ./.github/actions/build
        with:
          node_version: ${{ matrix.node_version }}
